name: Deploy GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Replace API Key
        run: |
        env:
          REACT_APP_API_KEY: ${{secrets.API_KEY}}
          REACT_APP_SPREAD_SHEET_ID: ${{secrets.SPREAD_SHEET_ID}}
          REACT_APP_GAS_ID: ${{secrets.GAS_ID}}
          REACT_APP_SUPABASE_URL: ${{secrets.REACT_APP_SUPABASE_URL}}
          REACT_APP_SUPABASE_KEY: ${{secrets.REACT_APP_SUPABASE_KEY}}